name: Fuzz

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Run Fuzzing
        run: |
          cargo fuzz run fuzz_amf0_body -- -max_total_time=180

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fuzz-failures
          path: fuzz/artifacts/